### PR TITLE
Fix Log4j patch

### PR DESCRIPTION
**Pull request by ghost**
Port's @Lucaskyy's changes to the log4j patch

### CODE REVIEW

**Comment by HeathLoganCampbell** [comment]
Thank youuu

**Comment by Sculas** [comment]
@Elierrr Did you remove the custom ConsoleAppender in the source? Needs to be removed, you need to use the original one or it won't compile and run.

**Comment by ghost** [comment]
> @Elierrr Did you remove the ConsoleAppender? Needs to be removed.

I did.

**Comment by Sculas** [comment]
All good!

**Pull request merged**
